PyErr_Occurred()
{
    return 0;
}
